### ISSUE TITLE
Difficulty building on M1 mac

### ISSUE THREAD

**Issue by rob-p** [jguhlin/minimap2-rs#81]
Hi @jguhlin,

  I encounter the following error when attempting to include the minimap2-rs crate when building on OSX on an M1 Mac (MacOS 13.4):

```
  = note: ld: warning: directory not found for option '-L/Users/rob/software_src/oarfish/target/release/build/libz-sys-388cc2f2b07c10b2/out/lib64'
          Undefined symbols for architecture arm64:
            "_gzclose", referenced from:
                _mm_bseq_close in libminimap2_sys-4b0173a9259d886d.rlib(aa1d8596991defc1-bseq.o)
            "_gzdopen", referenced from:
                _mm_bseq_open in libminimap2_sys-4b0173a9259d886d.rlib(aa1d8596991defc1-bseq.o)
            "_gzopen", referenced from:
                _mm_bseq_open in libminimap2_sys-4b0173a9259d886d.rlib(aa1d8596991defc1-bseq.o)
            "_gzread", referenced from:
                _ks_getuntil2 in libminimap2_sys-4b0173a9259d886d.rlib(aa1d8596991defc1-bseq.o)
                _kseq_read in libminimap2_sys-4b0173a9259d886d.rlib(aa1d8596991defc1-bseq.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Have you seen anything like this before? Any idea why the relevant libz functions might not be found?

Thanks!

**Comment by rob-p** [comment]
I was able to get this to compile by manually overriding the rust flags (as below), but that shouldn’t be necessary.  Any ideas why?

```
RUSTFLAGS=‘-C link-args=-lz’ cargo build —-release
```

**Comment by jguhlin** [comment]
Hmm that should be a change we can make in build.rs script for it.

I don't have a Mac to test on, but will take a stab at it soon

**Comment by jguhlin** [comment]
This is going to be in minimap2-sys, can you try again on a newer pull of the git branch? I don't have a mac to change, but -lz is almost always passed in now.

**Comment by rob-p** [comment]
Hi @jguhlin --- thanks for all of this progress! I'm able to build the latest `main` on my M1 Macbook without extra invocations. However, I will note that some tests seem to fail. However, this looks to be related from an expected file missing `yeast_idx.mmi`.  Any chance this could be included to see if all tests pass?  Here's the cargo test output:

```
running 24 tests
test tests::aligner_builder ... ok
test tests::aligner_builder_preset_with_threads ... ok
test tests::aligner_build_manually ... ok
test tests::aligner_builder_preset ... ok
test tests::create_index_file_missing ... ok
test tests::does_it_work ... ok
test tests::idxopt ... ok
test tests::aligner_between_threads ... FAILED
test tests::mapopt ... ok
test tests::rayon ... FAILED
test tests::shared_aligner ... FAILED
test tests::test_builder ... ok
test tests::test_mapping ... FAILED
test tests::test_strand_struct ... ok
test tests::test_alignment_score ... ok
test tests::test_struct_config ... ok
test tests::test_threadlocalbuffer ... ok
test tests::test_send ... ok
test tests::test_aligner_struct ... ok
test tests::test_mappy_output ... ok
test tests::test_mappy_output_no_md ... ok
test tests::test_with_seq ... ok
test tests::create_index ... ok
test tests::test_aligner_config_and_mapping ... ok

failures:

---- tests::aligner_between_threads stdout ----
thread 'tests::aligner_between_threads' panicked at src/lib.rs:1219:61:
called `Result::unwrap()` on an `Err` value: "File does not exist"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::rayon stdout ----
thread 'tests::rayon' panicked at src/lib.rs:1308:61:
called `Result::unwrap()` on an `Err` value: "File does not exist"

---- tests::shared_aligner stdout ----
thread 'tests::shared_aligner' panicked at src/lib.rs:1265:61:
called `Result::unwrap()` on an `Err` value: "File does not exist"

---- tests::test_mapping stdout ----
thread 'tests::test_mapping' panicked at src/lib.rs:1439:61:
called `Result::unwrap()` on an `Err` value: "File does not exist"


failures:
    tests::aligner_between_threads
    tests::rayon
    tests::shared_aligner
    tests::test_mapping

test result: FAILED. 20 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

**Comment by jguhlin** [comment]
@rob-p I have no idea why that file disappeared, but I've added it back. Give it another go!

Also try with --features htslib (separately) to double check some other tests too, please

**Comment by rob-p** [comment]
@jguhlin -- success! I guess the next thing is to test it out downstream in `oarfish` to ensure the results are identical to the fork.  I'll report back. I'll be happy to stop relying on our fork! Are all of the changes from [https://github.com/rob-p/minimap2-rs/tree/alignment-score](https://github.com/rob-p/minimap2-rs/tree/alignment-score) now in main?

**Comment by rob-p** [comment]
Hi @jguhlin; so to resolve the `minimap2-sys` issue above, I simply synced my fork's `main` with your `main` and set `minimap2-sys` to point to `0.1.19` rather than the local folder.

This allowed me to make the minor modifications necessary to `oarfish` and confirm that with your changes, everything looks to work and produces identical output to what my fork with changes had been producing! I'll test on MacOS now too just to make sure, but I think this looks good to go from our side. Looking forward to the new release. Thanks!

**Comment by rob-p** [comment]
Ok, I was able to solve the above by setting the environment variable `MACOSX_DEPLOYMENT_TARGET=13.1`, but now I'm back to the linking error on MacOS. 

```
  = note: Undefined symbols for architecture arm64:
            "_gzclose", referenced from:
                _mm_bseq_close in libminimap2_sys-f0716645218e5fe8.rlib(aa1d8596991defc1-bseq.o)
            "_gzdopen", referenced from:
                _mm_bseq_open in libminimap2_sys-f0716645218e5fe8.rlib(aa1d8596991defc1-bseq.o)
            "_gzopen", referenced from:
                _mm_bseq_open in libminimap2_sys-f0716645218e5fe8.rlib(aa1d8596991defc1-bseq.o)
            "_gzread", referenced from:
                _ks_getuntil2 in libminimap2_sys-f0716645218e5fe8.rlib(aa1d8596991defc1-bseq.o)
                _kseq_read in libminimap2_sys-f0716645218e5fe8.rlib(aa1d8596991defc1-bseq.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `oarfish` (bin "oarfish") due to 1 previous error
```

Of course, I can again work around this by ensuring zlib is passed explicitly to cargo, but it's unclear why it's missing by default.

**Comment by jguhlin** [comment]
I think 0.1.19 has the same problem, but the version on main should work.

Github CI has an M1 mac runner now and with yeast_ref.mmi back tests work again.
https://github.com/jguhlin/minimap2-rs/actions/runs/11979873830/job/33402948579

That's for macos-14 but I'll see about a -13 and 13-arm164 run here in a few.

As for easier dev experience when working with main branches of mm2 and mm2-sys, there's no good/easy way. I just have to set the paths manually. 

Which means setting the path of mm2 to a working version where that -sys also asks for the path directly. 

You'll see I've got this code:
minimap2-sys = { path = "./minimap2-sys" }

so you'll need to use that (sorry!)

--

All of the changes in https://github.com/rob-p/minimap2-rs/tree/alignment-score now, but I modified the map function to take directly a query name, and then some hacky code to not allocate if it's a valid CStr/CString, and query name/target name from mappings are returned as Arc's to reduce allocations for large runs. I'm curious to see if that's too much of a pain for people, but I'm working with some >10Gb genomes with high repeat content.... hah.

Going to tackle #71 before I push a release out.

**Comment by rob-p** [comment]
> minimap2-sys = { path = "./minimap2-sys" }

If you put minimap2-sys in its own repo, then you can point to that directly in cargo.

Cargo is smart enough that it will use the GitHub repo as the source during dev, but switch to the published crate once you push minimap2-rs to crates.io. I use that strategy quite successfully ;P.

**Comment by jguhlin** [comment]
Oh that's cool. But all the other ffi crates keep everything in one repo. I
wonder if there's a way to make that work

**Comment by rob-p** [comment]
Hi @jguhlin : I just implemented this in my for on the main branch [here](https://github.com/rob-p/minimap2-rs).  Note that the `Cargo.toml` now points to an external [minimap2-sys](https://github.com/rob-p/minimap2-sys) repo.  This allows a project that depends on both `minimap2-rs` and `minimap2-sys` to declare a *dev* version of both (e.g. for testing).

This should work just as easy as keeping the minimap2-sys directly in minimap2-rs, and potentially even easier as you don't even have to muck with `Cargo.toml` prior to release. The only thing you have to do is to make sure that if you want to bump `minimap2-sys` in a new version of `minimap2-rs` you have to push `sys` to crates.io before the main crate.

**Comment by jguhlin** [comment]
Nice. I'll check it out!

**Comment by jianshu93** [comment]
Hi all,
Same problem with clang here. With this: RUSTFLAGS='-C link-args=-lz' cargo build

the problem seems to be solved (Clang 19.1.3, just build, no actual use from other crates)

But I think with GCC I have no problems on M series chip. Does clang provide better performance for M1 series chip?

CC="$(brew --prefix)/bin/gcc-14" CXX="$(brew --prefix)/bin/g++-14" cargo build --release


Since minimap2 was built natively via GNU GCC, we should just use GNU GCC for convenience on M series?

Best,
Jianshu

**Comment by jguhlin** [comment]
@jianshu93 Are you having the same problem with building the latest main branch?

**Comment by jguhlin** [comment]
Awesome. Thx for checking

**Comment by jianshu93** [comment]
The only warning is that u128 is not FFI safe: see below:


warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7242:10
     |
7242 |     ) -> u128;
     |          ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI
     = note: `#[warn(improper_ctypes)]` on by default

warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7787:18
     |
7787 |         __value: u128,
     |                  ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI

warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7795:18
     |
7795 |         __value: u128,
     |                  ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI

warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7803:18
     |
7803 |         __value: u128,
     |                  ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI

warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7830:18
     |
7830 |         __value: u128,
     |                  ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI

warning: `extern` block uses type `u128`, which is not FFI-safe
    --> minimap2-sys/src/bindings.rs:7840:18
     |
7840 |         __value: u128,
     |                  ^^^^ not FFI-safe
     |
     = note: 128-bit integers don't currently have a known stable ABI

warning: `minimap2-sys` (lib) generated 6 warnings



It did compile however.  Not sure how to avoid this warning or we have to wait until there is a stable ABI for 128-bit integers. 

Best,
Jianshu

**Comment by rob-p** [comment]
I get these same warnings, but otherwise, everything compiles cleanly for me too.

**Comment by rob-p** [comment]
I think these warnings are due to the lack of guarantees on the stability of this FFI layout on the aarch64 platform in general.  As such, we probably won't be able to properly "handle" them here. We could silence them, but that doesn't seem great.  I think this is not a `minimap2-rs` issue and the original issue is now resolved, so please feel free to close this issue!

**Comment by jguhlin** [comment]
It happens on x86 as well. I'm not going to silence them in case something
changes. I don't think there is a fix, u128 alignments are ffi compatible
on x86 since 1.77 now but the warning still shows.

Im going to close this and a host of other issues with a release. But feel
free to open any back up if Im overzealous! :)
